# Práctica 1: Perceptrón

In [1]:
# Imports

# Si se usa colab usar este try
#try:
#  %tensorflow_version 2.x
#except Exception:
#  pass

import tensorflow as tf
print(tf.__version__)

from tensorflow import keras

2.1.0


## 1.1 Una instancia del problema del cine

1. Crea una instancia del problema del cine visto en las diapositivas (ej. [clima=1, lugar=-1, pareja=-1] --> voy
).
2. Implementa un perceptrón en Keras usando una capa densa con una unidad y función de activación lineal. A la salida del perceptrón aplica la función signo.
3. Verifica que la solución del pizarrón y de la implementación en Keras coincidan.

In [13]:
# Creación de datos
# [clima=1, lugar=-1, pareja=-1] --> voy
data = tf.constant([[1.,-1.,-1.]]) # batch

print(data)

tf.Tensor([[ 1. -1. -1.]], shape=(1, 3), dtype=float32)


In [14]:
# Implementación del perceptrón
from tensorflow.keras.layers import Dense
perceptron = Dense(units=1,
              activation="linear",
              use_bias=True,
              kernel_initializer=tf.keras.initializers.constant([3.,1.,1.]), # <-- ¿pesos? #Ponemos el kernel
              bias_initializer=tf.keras.initializers.constant([2.])) # <-- ¿bias? # Ponemos el bias

# Aplicamos el model modelo a nuestros datos
result = perceptron(data)
print(result)

tf.Tensor([[3.]], shape=(1, 1), dtype=float32)


In [15]:
# Función signo # si sale 1 vamos al cine, si sale -1 no vamos :( )
result = tf.math.sign(result)
print(result)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


## 1.2 Todas las instancias del problema del cine

1. Crea todas instancias del problema del cine visto en las diapositivas.
2. Implementa un perceptrón en Keras usando una capa densa con una unidad y función de activación lineal. A la salida del perceptrón aplica la función signo.
3. Verifica que la solución del pizarrón y de la implementación en Keras coincidan.

Instancias:
* [clima=-1, lugar=-1, pareja=-1] --> No
* [clima=-1, lugar=-1, pareja=1] --> No
* [clima=-1, lugar=1, pareja=-1] --> No
* [clima=-1, lugar=1, pareja=1] --> Sí
* [clima=1, lugar=-1, pareja=-1] --> Sí
* [clima=1, lugar=-1, pareja=1] --> Sí
* [clima=1, lugar=1, pareja=-1] --> Sí
* [clima=1, lugar=1, pareja=1] --> Sí

In [17]:
# Creación de datos
data = tf.constant([[-1,-1,-1],
                     [-1,-1,1],
                     [-1,1,-1],
                     [-1,1,1],
                     [1,-1,-1],
                     [1,-1,1],
                     [1,1,-1],
                     [1,1,1]]) # batch

print(data)

tf.Tensor(
[[-1 -1 -1]
 [-1 -1  1]
 [-1  1 -1]
 [-1  1  1]
 [ 1 -1 -1]
 [ 1 -1  1]
 [ 1  1 -1]
 [ 1  1  1]], shape=(8, 3), dtype=int32)


In [18]:
# Implementación del perceptrón
from tensorflow.keras.layers import Dense
perceptron = Dense(units=1,
              activation="linear",
              use_bias=True,
              kernel_initializer=tf.keras.initializers.constant([3.,1.,1.]), # <-- ¿pesos? 
              bias_initializer=tf.keras.initializers.constant([2.])) # <-- ¿bias? 

# Aplicamos el model modelo a nuestros datos
result = perceptron(data)

print(result)

tf.Tensor(
[[-3.]
 [-1.]
 [-1.]
 [ 1.]
 [ 3.]
 [ 5.]
 [ 5.]
 [ 7.]], shape=(8, 1), dtype=float32)


In [19]:
# Función signo
result = tf.math.sign(result)
print(result)

tf.Tensor(
[[-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]], shape=(8, 1), dtype=float32)
