# Práctica 2: Funciones de activación

In [2]:
# Imports

# Si se usa colab usar este try
#try:
#  %tensorflow_version 2.x
#except Exception:
#  pass

import tensorflow as tf
print(tf.__version__)

from tensorflow import keras

2.1.0


In [4]:
# Creación de datos

data = tf.constant([[1.,1.,1.]]) # batch

print(data)

tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)


## 1.1 Activación sigmoide

Ajustar los pesos para obtener con sigmoide (activation="sigmoid") salidas de 0, 0.5, 1

In [13]:
# Implementación del perceptrón
from tensorflow.keras.layers import Dense
perceptron = Dense(units=1,
              activation="sigmoid",#si queremos ligistica es sigmoid
              use_bias=True,
              kernel_initializer=tf.keras.initializers.constant([0.01,0,0.1]), # <--- [w1,w2,w3]
              bias_initializer=tf.keras.initializers.constant([-20])) # <--- [b]

# Aplicamos el model modelo a nuestros datos
result = perceptron(data)
print(result)

tf.Tensor([[2.300822e-09]], shape=(1, 1), dtype=float32)


In [25]:
# Implementación del perceptrón
from tensorflow.keras.layers import Dense
perceptron = Dense(units=1,
              activation="sigmoid",#si queremos ligistica es sigmoid
              use_bias=True,
              kernel_initializer=tf.keras.initializers.constant([0.1,0.3,0.01]), # <--- [w1,w2,w3]
              bias_initializer=tf.keras.initializers.constant([0.1])) # <--- [b]

# Aplicamos el model modelo a nuestros datos
result = perceptron(data)
print(result)

tf.Tensor([[0.62480646]], shape=(1, 1), dtype=float32)


In [33]:
# Implementación del perceptrón
from tensorflow.keras.layers import Dense
perceptron = Dense(units=1,
              activation="sigmoid",#si queremos ligistica es sigmoid
              use_bias=True,
              kernel_initializer=tf.keras.initializers.constant([0.8,0.9,0.8]), # <--- [w1,w2,w3]
              bias_initializer=tf.keras.initializers.constant([1])) # <--- [b]

# Aplicamos el model modelo a nuestros datos
result = perceptron(data)
print(result)

tf.Tensor([[0.97068775]], shape=(1, 1), dtype=float32)


## 1.2 Activación tanh

Ajustar los pesos para obtener con tanh (activation="tanh") salidas de -1, 0, 1

In [41]:
# Implementación del perceptrón
from tensorflow.keras.layers import Dense
perceptron = Dense(units=1,
              activation="tanh",
              use_bias=True,
              kernel_initializer=tf.keras.initializers.constant([0.01,0.01,0.01]), # <--- [w1,w2,w3]
              bias_initializer=tf.keras.initializers.constant([-100])) # <--- [b]

# Aplicamos el model modelo a nuestros datos
result = perceptron(data)
print(result)

tf.Tensor([[-1.]], shape=(1, 1), dtype=float32)


## 1.3 Activación ReLu

Ajustar los pesos para obtener con ReLu (activation="relu") salidas de 0, lineal

In [42]:
# Implementación del perceptrón
from tensorflow.keras.layers import Dense
perceptron = Dense(units=1,
              activation="relu",
              use_bias=True,
              kernel_initializer=tf.keras.initializers.constant([1,1,1]), # <--- [w1,w2,w3]
              bias_initializer=tf.keras.initializers.constant([5])) # <--- [b]

# Aplicamos el model modelo a nuestros datos
result = perceptron(data)
print(result)

tf.Tensor([[8.]], shape=(1, 1), dtype=float32)


In [43]:
# Implementación del perceptrón
from tensorflow.keras.layers import Dense
perceptron = Dense(units=1,
              activation="relu",
              use_bias=True,
              kernel_initializer=tf.keras.initializers.constant([1,1,1]), # <--- [w1,w2,w3]
              bias_initializer=tf.keras.initializers.constant([-5])) # <--- [b]

# Aplicamos el model modelo a nuestros datos
result = perceptron(data)
print(result)

tf.Tensor([[0.]], shape=(1, 1), dtype=float32)


Para clasificacion binaria (dato no dato, 0 o 1):

- para la clasificacion podemos usar entropia cruzada(** checar que es)
- Para salida podemos usar sigmoide

Capa final, distribucion de probabilidad ( cheacar cuando aplicar, clasificasion multiclase ) 
**Entropia cruzada: 